package org.aguerra.cookedham.interpret.lex;

public enum Type {
    // Single-character tokens
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE, LEFT_BRACKET,
    RIGHT_BRACKET, COMMA, DOT, SEMICOLON, COLON, ASSIGN, PLUS, MINUS,
    STAR, SLASH, MOD, LEFT_ANGLE_BRACE, RIGHT_ANGLE_BRACE, NOT,
    AMPERSAND, PIPE, XOR, TILDA, QUESTION,

    // Two character tokens
    PLUS_ASSIGN, MINUS_ASSIGN, STAR_ASSIGN, SLASH_ASSIGN,
    MOD_ASSIGN, POW, EQUALS, GREATER_EQUAL, LESSER_EQUAL,
    NOT_EQUAL, AND, OR, LEFT_SHIFT, RIGHT_SHIFT,

    // Literals
    INT_LITERAL, DECIMAL_LITERAL, CHAR_LITERAL, STRING_LITERAL,

    // Data Types and Identifier
    INT, DECIMAL, CHAR, STRING, BOOLEAN, IDENTIFIER, ARRAY, VOID,

    // Keywords
    BREAK, CLASS, CONST, ELSE, FALSE, FOR, IF, NULL, RETURN, SUPER,
    THIS, TRUE, WHILE, PRINT, LEN,

    EOF,
}